apiVersion: ingress.zhiyuanzhou.cloud/v1beta1
kind: App
metadata:
  name: app-sample
spec:
  # TODO(user): Add fields here
  image: nginx:latest
  replicas: 2
  enable_ingress: true #会被修改为true
  enable_service: true #成功